CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    frame VARCHAR(50) NOT NULL,
    lenses VARCHAR(50) NOT NULL,
    work_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    working_time BIGINT NOT NULL
);

